// Multiple Root Layouts: It will only work perfectly if we move layout.tsx and page.tsx from root folder app to else where, otherwise both Layouts will be displayed.
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h2>Customised Header for Auth Pages</h2>
        {children}
      </body>
    </html>
  )
}
